version: "3.2"
services:
  electron-dev:
    container_name: vue-electron-dev
    build: 
      context: .
      args:
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ./volumes/nodejs:/home/node
      - /tmp/.X11-unix/:/tmp/.X11-unix/:cached
    ports: 
      - 8002:8080
    privileged: true
    tty: true
    environment:
      - DISPLAY=:0
      - TZ=Asia/Tokyo
